import tkinter as tk
from tkinter import messagebox
def login(username_entry, password_entry):
    username = username_entry.get()
    password = password_entry.get()
    messagebox.showinfo("Mensaje", "Inicio de sesión exitoso")
def show_login_screen():
    login_window = tk.Toplevel(ventana)
    login_window.title("Iniciar Sesión")
    login_window.geometry("500x400")
    username_label = tk.Label(login_window, text="Usuario:")
    username_label.pack()
    username_entry = tk.Entry(login_window)
    username_entry.pack()
    password_label = tk.Label(login_window, text="Contraseña:")
    password_label.pack()
    password_entry = tk.Entry(login_window, show="*")
    password_entry.pack()
    login_button = tk.Button(login_window, text="Iniciar Sesión", command=lambda: login(username_entry, password_entry))
    login_button.pack()
def show_register_screen():
    register_window = tk.Toplevel(ventana)
    register_window.title("Registrarse")
    register_window.geometry("500x400")
    new_username_label = tk.Label(register_window, text="Nuevo Usuario:")
    new_username_label.pack()
    new_username_entry = tk.Entry(register_window)
    new_username_entry.pack()
    new_password_label = tk.Label(register_window, text="Nueva Contraseña:")
    new_password_label.pack()
    new_password_entry = tk.Entry(register_window, show="*")
    new_password_entry.pack()
    register_button = tk.Button(register_window, text="Registrarse", command=lambda: register(new_username_entry, new_password_entry))
    register_button.pack()
ventana = tk.Tk()
ventana.title("Sistema de Inicio de Sesión")
ventana.geometry("500x400")
login_button = tk.Button(ventana, text="Iniciar Sesión", command=show_login_screen)
login_button.pack(pady=20)
register_button = tk.Button(ventana, text="Registrarse", command=show_register_screen)
register_button.pack(pady=20)
ventana.mainloop()
